class SackImage{
    constructor(path, category){
        this.path=path;
        this.category=category;
    }
}

ImagePaths =[
new SackImage("Beach (2).JPG","beach"),
new SackImage("Beach(3).jpg","beach"),
new SackImage("Beach.JPG","beach"),
new SackImage("Bowling1.JPG","bowling"),
new SackImage("Bowling2.JPG","bowling"),
new SackImage("Bowling3.JPG","bowling"),
new SackImage("Dates (1).jpg","dates"),
new SackImage("Dates (2).jpg","dates"),
new SackImage("Dates (3).jpg","dates"),
new SackImage("Dates (4).jpg","dates"),
new SackImage("Dates (5).jpg","dates"),
new SackImage("Dates (6).jpg","dates"),
new SackImage("Dog (2).JPG","dog"),
new SackImage("Dog (3).JPG","dog"),
new SackImage("Dog (4).jpg","dog"),
new SackImage("Dog.JPG","dog"),
new SackImage("EarlyDays (2).JPG","early days"),
new SackImage("EarlyDays (3).JPG","early days"),
new SackImage("EarlyDays (4).JPG","early days"),
new SackImage("EarlyDays (5).JPG","early days"),
new SackImage("EarlyDays (6).jpg","early days"),
new SackImage("EarlyDays (7).jpg","early days"),
new SackImage("EarlyDays.JPG","early days"),
new SackImage("Em (2).jpg","em"),
new SackImage("Em(3).jpg","em"),
new SackImage("Em.JPG","em"),
new SackImage("Food (2).JPG","food"),
new SackImage("Food.JPG","food"),
new SackImage("Funny (1).jpg","funny"),
new SackImage("Funny (10).jpg","funny"),
new SackImage("Funny (2).JPG","funny"),
new SackImage("Funny (3).JPG","funny"),
new SackImage("Funny (4).JPG","funny"),
new SackImage("Funny (5).JPG","funny"),
new SackImage("Funny (6).JPG","funny"),
new SackImage("Funny (7).JPG","funny"),
new SackImage("Funny (9).jpg","funny"),
new SackImage("Funny(8).jpg","funny"),
new SackImage("Funny.JPG","funny"),
new SackImage("Gym (2).jpg","gym"),
new SackImage("Gym.jpg","gym"),
new SackImage("MakeUp1.JPG","makeup"),
new SackImage("MakeUp2.JPG","makeup"),
new SackImage("MakeUp3.JPG","makeup"),
new SackImage("Prom (2).JPEG","prom"),
new SackImage("Prom (2).JPG","prom"),
new SackImage("Prom (3).JPG","prom"),
new SackImage("Prom (4).JPG","prom"),
new SackImage("Prom (5).JPG","prom"),
new SackImage("Prom.JPEG","prom"),
new SackImage("Prom.JPG","prom"),
new SackImage("Sleep (1).JPG","sleep"),
new SackImage("Sleep (2).JPG","sleep"),
new SackImage("Sleep (3).JPG","sleep"),
new SackImage("Sleep(3).jpg","sleep"),
new SackImage("Sleep.JPG","sleep"),
new SackImage("SydJack (2).JPG","syd and jack"),
new SackImage("SydJack (3).JPG","syd and jack"),
new SackImage("SydJack (4).JPG","syd and jack"),
new SackImage("SydJack (5).JPG","syd and jack"),
new SackImage("SydJack (7).jpg","syd and jack"),
new SackImage("SydJack (8).jpg","syd and jack"),
new SackImage("SydJack (9).jpg","syd and jack"),
new SackImage("SydJack(6).jpg","syd and jack"),
new SackImage("SydJack.JPG","syd and jack"),
new SackImage("Wedding (2).jpg","wedding"),
new SackImage("wedding(1).jpg","wedding"),
new SackImage("Wedding.JPG","wedding")
]
VideoPaths=[
    "Beach.MOV",
    "Em.MOV",
    "Funny.MOV",
    "Funny(2).MOV"
]


