ImagePaths =[
"Beach (2).JPG",
"Beach(3).jpg",
"Beach.JPG",
"Bowling1.JPG",
"Bowling2.JPG",
"Bowling3.JPG",
"Cute.JPG",
"Dates (1).jpg",
"Dates (2).jpg",
"Dates (3).jpg",
"Dates (4).jpg",
"Dates (5).jpg",
"Dates (6).jpg",
"Dog (2).JPG",
"Dog (3).JPG",
"Dog (4).jpg",
"Dog.JPG",
"EarlyDays (2).JPG",
"EarlyDays (3).JPG",
"EarlyDays (4).JPG",
"EarlyDays (5).JPG",
"EarlyDays (6).jpg",
"EarlyDays (7).jpg",
"EarlyDays.JPG",
"Em (2).jpg",
"Em(3).jpg",
"Em.JPG",
"Food (2).JPG",
"Food.JPG",
"Funny (1).jpg",
"Funny (10).jpg",
"Funny (2).JPG",
"Funny (3).JPG",
"Funny (4).JPG",
"Funny (5).JPG",
"Funny (6).JPG",
"Funny (7).JPG",
"Funny (9).jpg",
"Funny(8).jpg",
"Funny.JPG",
"Gym (2).jpg",
"Gym.jpg",
"MakeUp1.JPG",
"MakeUp2.JPG",
"MakeUp3.JPG",
"Prom (2).JPEG",
"Prom (2).JPG",
"Prom (3).JPG",
"Prom (4).JPG",
"Prom (5).JPG",
"Prom.JPEG",
"Prom.JPG",
"Sleep (1).JPG",
"Sleep (2).JPG",
"Sleep (3).JPG",
"Sleep(3).jpg",
"Sleep.JPG",
"SydInJacksClothes.JPG",
"SydJack (2).JPG",
"SydJack (3).JPG",
"SydJack (4).JPG",
"SydJack (5).JPG",
"SydJack (7).jpg",
"SydJack (8).jpg",
"SydJack (9).jpg",
"SydJack(6).jpg",
"SydJack.JPG",
"Wedding (2).jpg",
"wedding(1).jpg",
"Wedding.JPG"]

VideoPaths=[
    "Beach.MOV",
    "Em.MOV",
    "Funny.MOV",
    "Funny(2).MOV"
]